### ISSUE TITLE
Frontend fixes

### ISSUE THREAD

**Issue by core2pl** [MisterMagister/symfony2-start#2]
Currently frontend isn't looking preety good.

**Comment by MisterMagister** [comment]
fixed

**Comment by core2pl** [comment]
login/register forms are still not using bootstrap

remove br tag from spaces between forms inputs

**Comment by core2pl** [comment]
There is no direct link for any gallery from index page
